### ISSUE TITLE
Help us translate the BeAPI website

### ISSUE THREAD

**Issue by nobu-sh** [MCBE-Utilities/BeAPI#33]
`Last updated: 4/2/2021`

## Help us translate the BeAPI website
BeAPIs website uses a documentation framework called [Docusaurus](https://github.com/facebook/docusaurus).
Docusaurus v2 is completely i18n localization ready. With that being said we want to translate BeAPIs website for
our non fluent English users.

## Roadmap before translation ready
- [ ] Possible CLI translations via os locale [^nodeLocale]
- [x] Register BeAPI for Crowdin open-source plan [^crowdinPlan]
- [ ] Integrate Crowdin with Docusaurus i18n [^docCrowdin]
- [ ] Spend countless hours blacklisting mdx keys in Crowdin ;-;
- [ ] Reach out to other communities to help translate :) 

## Translation process
- Optionally get familiar with the [Docusaurus i18n support](https://docusaurus.io/docs/i18n/introduction)
- Ensure your language is also translated for the CLI (Prioritize CLI translations first)
- Sign-up on [Crowdin](https://crowdin.com/) and join the [BeAPI](https://crowdin.com/project/beapi) project
- Get familiar with the Crowdin translation UI, as you will need to use it to translate JSON and Markdown files
- Ask for your locale to be enabled on Crowdin (if not already enabled)
- Translate the content

### More info will be made available once roadmap is complete!

[^nodeLocale]:
      Example of getting OS locale through node:
      ```js
      const env = process.env;
      const language = env.LANG || env.LANGUAGE || env.LC_ALL || env.LC_MESSAGES;
      ```
[^crowdinPlan]:
     Crowdin offers a free plan for open source projects, [read more here](https://crowdin.com/page/open-source-project-setup-request).

[^docCrowdin]:
    Implementation documentation located [here](https://docusaurus.io/docs/i18n/crowdin).
